// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: statistics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatType int32

const (
	StatType_VIEWS    StatType = 0
	StatType_LIKES    StatType = 1
	StatType_COMMENTS StatType = 2
)

// Enum value maps for StatType.
var (
	StatType_name = map[int32]string{
		0: "VIEWS",
		1: "LIKES",
		2: "COMMENTS",
	}
	StatType_value = map[string]int32{
		"VIEWS":    0,
		"LIKES":    1,
		"COMMENTS": 2,
	}
)

func (x StatType) Enum() *StatType {
	p := new(StatType)
	*p = x
	return p
}

func (x StatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatType) Descriptor() protoreflect.EnumDescriptor {
	return file_statistics_proto_enumTypes[0].Descriptor()
}

func (StatType) Type() protoreflect.EnumType {
	return &file_statistics_proto_enumTypes[0]
}

func (x StatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatType.Descriptor instead.
func (StatType) EnumDescriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{0}
}

type GetPostStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostStatsRequest) Reset() {
	*x = GetPostStatsRequest{}
	mi := &file_statistics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostStatsRequest) ProtoMessage() {}

func (x *GetPostStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostStatsRequest.ProtoReflect.Descriptor instead.
func (*GetPostStatsRequest) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{0}
}

func (x *GetPostStatsRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type GetPostStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	ViewsCount    int32                  `protobuf:"varint,2,opt,name=views_count,json=viewsCount,proto3" json:"views_count,omitempty"`
	LikesCount    int32                  `protobuf:"varint,3,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	CommentsCount int32                  `protobuf:"varint,4,opt,name=comments_count,json=commentsCount,proto3" json:"comments_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostStatsResponse) Reset() {
	*x = GetPostStatsResponse{}
	mi := &file_statistics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostStatsResponse) ProtoMessage() {}

func (x *GetPostStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostStatsResponse.ProtoReflect.Descriptor instead.
func (*GetPostStatsResponse) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{1}
}

func (x *GetPostStatsResponse) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *GetPostStatsResponse) GetViewsCount() int32 {
	if x != nil {
		return x.ViewsCount
	}
	return 0
}

func (x *GetPostStatsResponse) GetLikesCount() int32 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

func (x *GetPostStatsResponse) GetCommentsCount() int32 {
	if x != nil {
		return x.CommentsCount
	}
	return 0
}

type GetPostTimelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostTimelineRequest) Reset() {
	*x = GetPostTimelineRequest{}
	mi := &file_statistics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostTimelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostTimelineRequest) ProtoMessage() {}

func (x *GetPostTimelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostTimelineRequest.ProtoReflect.Descriptor instead.
func (*GetPostTimelineRequest) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{2}
}

func (x *GetPostTimelineRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *GetPostTimelineRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetPostTimelineRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type TimelinePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelinePoint) Reset() {
	*x = TimelinePoint{}
	mi := &file_statistics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelinePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelinePoint) ProtoMessage() {}

func (x *TimelinePoint) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelinePoint.ProtoReflect.Descriptor instead.
func (*TimelinePoint) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{3}
}

func (x *TimelinePoint) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TimelinePoint) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetTimelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Points        []*TimelinePoint       `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimelineResponse) Reset() {
	*x = GetTimelineResponse{}
	mi := &file_statistics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimelineResponse) ProtoMessage() {}

func (x *GetTimelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimelineResponse.ProtoReflect.Descriptor instead.
func (*GetTimelineResponse) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{4}
}

func (x *GetTimelineResponse) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *GetTimelineResponse) GetPoints() []*TimelinePoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type GetTopPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatType      StatType               `protobuf:"varint,1,opt,name=stat_type,json=statType,proto3,enum=statistics.StatType" json:"stat_type,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopPostsRequest) Reset() {
	*x = GetTopPostsRequest{}
	mi := &file_statistics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPostsRequest) ProtoMessage() {}

func (x *GetTopPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPostsRequest.ProtoReflect.Descriptor instead.
func (*GetTopPostsRequest) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{5}
}

func (x *GetTopPostsRequest) GetStatType() StatType {
	if x != nil {
		return x.StatType
	}
	return StatType_VIEWS
}

func (x *GetTopPostsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TopPost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopPost) Reset() {
	*x = TopPost{}
	mi := &file_statistics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPost) ProtoMessage() {}

func (x *TopPost) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPost.ProtoReflect.Descriptor instead.
func (*TopPost) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{6}
}

func (x *TopPost) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *TopPost) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TopPost) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetTopPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*TopPost             `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopPostsResponse) Reset() {
	*x = GetTopPostsResponse{}
	mi := &file_statistics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPostsResponse) ProtoMessage() {}

func (x *GetTopPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPostsResponse.ProtoReflect.Descriptor instead.
func (*GetTopPostsResponse) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{7}
}

func (x *GetTopPostsResponse) GetPosts() []*TopPost {
	if x != nil {
		return x.Posts
	}
	return nil
}

type GetTopUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatType      StatType               `protobuf:"varint,1,opt,name=stat_type,json=statType,proto3,enum=statistics.StatType" json:"stat_type,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopUsersRequest) Reset() {
	*x = GetTopUsersRequest{}
	mi := &file_statistics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopUsersRequest) ProtoMessage() {}

func (x *GetTopUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopUsersRequest.ProtoReflect.Descriptor instead.
func (*GetTopUsersRequest) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{8}
}

func (x *GetTopUsersRequest) GetStatType() StatType {
	if x != nil {
		return x.StatType
	}
	return StatType_VIEWS
}

func (x *GetTopUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TopUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUser) Reset() {
	*x = TopUser{}
	mi := &file_statistics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUser) ProtoMessage() {}

func (x *TopUser) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUser.ProtoReflect.Descriptor instead.
func (*TopUser) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{9}
}

func (x *TopUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TopUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TopUser) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetTopUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*TopUser             `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopUsersResponse) Reset() {
	*x = GetTopUsersResponse{}
	mi := &file_statistics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopUsersResponse) ProtoMessage() {}

func (x *GetTopUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopUsersResponse.ProtoReflect.Descriptor instead.
func (*GetTopUsersResponse) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{10}
}

func (x *GetTopUsersResponse) GetUsers() []*TopUser {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_statistics_proto protoreflect.FileDescriptor

const file_statistics_proto_rawDesc = "" +
	"\n" +
	"\x10statistics.proto\x12\n" +
	"statistics\".\n" +
	"\x13GetPostStatsRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x04R\x06postId\"\x98\x01\n" +
	"\x14GetPostStatsResponse\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x04R\x06postId\x12\x1f\n" +
	"\vviews_count\x18\x02 \x01(\x05R\n" +
	"viewsCount\x12\x1f\n" +
	"\vlikes_count\x18\x03 \x01(\x05R\n" +
	"likesCount\x12%\n" +
	"\x0ecomments_count\x18\x04 \x01(\x05R\rcommentsCount\"k\n" +
	"\x16GetPostTimelineRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x04R\x06postId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"9\n" +
	"\rTimelinePoint\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"a\n" +
	"\x13GetTimelineResponse\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x04R\x06postId\x121\n" +
	"\x06points\x18\x02 \x03(\v2\x19.statistics.TimelinePointR\x06points\"]\n" +
	"\x12GetTopPostsRequest\x121\n" +
	"\tstat_type\x18\x01 \x01(\x0e2\x14.statistics.StatTypeR\bstatType\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"N\n" +
	"\aTopPost\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x04R\x06postId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"@\n" +
	"\x13GetTopPostsResponse\x12)\n" +
	"\x05posts\x18\x01 \x03(\v2\x13.statistics.TopPostR\x05posts\"]\n" +
	"\x12GetTopUsersRequest\x121\n" +
	"\tstat_type\x18\x01 \x01(\x0e2\x14.statistics.StatTypeR\bstatType\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"T\n" +
	"\aTopUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"@\n" +
	"\x13GetTopUsersResponse\x12)\n" +
	"\x05users\x18\x01 \x03(\v2\x13.statistics.TopUserR\x05users*.\n" +
	"\bStatType\x12\t\n" +
	"\x05VIEWS\x10\x00\x12\t\n" +
	"\x05LIKES\x10\x01\x12\f\n" +
	"\bCOMMENTS\x10\x022\xa0\x04\n" +
	"\x11StatisticsService\x12Q\n" +
	"\fGetPostStats\x12\x1f.statistics.GetPostStatsRequest\x1a .statistics.GetPostStatsResponse\x12[\n" +
	"\x14GetPostViewsTimeline\x12\".statistics.GetPostTimelineRequest\x1a\x1f.statistics.GetTimelineResponse\x12[\n" +
	"\x14GetPostLikesTimeline\x12\".statistics.GetPostTimelineRequest\x1a\x1f.statistics.GetTimelineResponse\x12^\n" +
	"\x17GetPostCommentsTimeline\x12\".statistics.GetPostTimelineRequest\x1a\x1f.statistics.GetTimelineResponse\x12N\n" +
	"\vGetTopPosts\x12\x1e.statistics.GetTopPostsRequest\x1a\x1f.statistics.GetTopPostsResponse\x12N\n" +
	"\vGetTopUsers\x12\x1e.statistics.GetTopUsersRequest\x1a\x1f.statistics.GetTopUsersResponseB\x0eZ\fcommon/protob\x06proto3"

var (
	file_statistics_proto_rawDescOnce sync.Once
	file_statistics_proto_rawDescData []byte
)

func file_statistics_proto_rawDescGZIP() []byte {
	file_statistics_proto_rawDescOnce.Do(func() {
		file_statistics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_statistics_proto_rawDesc), len(file_statistics_proto_rawDesc)))
	})
	return file_statistics_proto_rawDescData
}

var file_statistics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_statistics_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_statistics_proto_goTypes = []any{
	(StatType)(0),                  // 0: statistics.StatType
	(*GetPostStatsRequest)(nil),    // 1: statistics.GetPostStatsRequest
	(*GetPostStatsResponse)(nil),   // 2: statistics.GetPostStatsResponse
	(*GetPostTimelineRequest)(nil), // 3: statistics.GetPostTimelineRequest
	(*TimelinePoint)(nil),          // 4: statistics.TimelinePoint
	(*GetTimelineResponse)(nil),    // 5: statistics.GetTimelineResponse
	(*GetTopPostsRequest)(nil),     // 6: statistics.GetTopPostsRequest
	(*TopPost)(nil),                // 7: statistics.TopPost
	(*GetTopPostsResponse)(nil),    // 8: statistics.GetTopPostsResponse
	(*GetTopUsersRequest)(nil),     // 9: statistics.GetTopUsersRequest
	(*TopUser)(nil),                // 10: statistics.TopUser
	(*GetTopUsersResponse)(nil),    // 11: statistics.GetTopUsersResponse
}
var file_statistics_proto_depIdxs = []int32{
	4,  // 0: statistics.GetTimelineResponse.points:type_name -> statistics.TimelinePoint
	0,  // 1: statistics.GetTopPostsRequest.stat_type:type_name -> statistics.StatType
	7,  // 2: statistics.GetTopPostsResponse.posts:type_name -> statistics.TopPost
	0,  // 3: statistics.GetTopUsersRequest.stat_type:type_name -> statistics.StatType
	10, // 4: statistics.GetTopUsersResponse.users:type_name -> statistics.TopUser
	1,  // 5: statistics.StatisticsService.GetPostStats:input_type -> statistics.GetPostStatsRequest
	3,  // 6: statistics.StatisticsService.GetPostViewsTimeline:input_type -> statistics.GetPostTimelineRequest
	3,  // 7: statistics.StatisticsService.GetPostLikesTimeline:input_type -> statistics.GetPostTimelineRequest
	3,  // 8: statistics.StatisticsService.GetPostCommentsTimeline:input_type -> statistics.GetPostTimelineRequest
	6,  // 9: statistics.StatisticsService.GetTopPosts:input_type -> statistics.GetTopPostsRequest
	9,  // 10: statistics.StatisticsService.GetTopUsers:input_type -> statistics.GetTopUsersRequest
	2,  // 11: statistics.StatisticsService.GetPostStats:output_type -> statistics.GetPostStatsResponse
	5,  // 12: statistics.StatisticsService.GetPostViewsTimeline:output_type -> statistics.GetTimelineResponse
	5,  // 13: statistics.StatisticsService.GetPostLikesTimeline:output_type -> statistics.GetTimelineResponse
	5,  // 14: statistics.StatisticsService.GetPostCommentsTimeline:output_type -> statistics.GetTimelineResponse
	8,  // 15: statistics.StatisticsService.GetTopPosts:output_type -> statistics.GetTopPostsResponse
	11, // 16: statistics.StatisticsService.GetTopUsers:output_type -> statistics.GetTopUsersResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_statistics_proto_init() }
func file_statistics_proto_init() {
	if File_statistics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_statistics_proto_rawDesc), len(file_statistics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_statistics_proto_goTypes,
		DependencyIndexes: file_statistics_proto_depIdxs,
		EnumInfos:         file_statistics_proto_enumTypes,
		MessageInfos:      file_statistics_proto_msgTypes,
	}.Build()
	File_statistics_proto = out.File
	file_statistics_proto_goTypes = nil
	file_statistics_proto_depIdxs = nil
}
