// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: statistics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatisticsService_GetPostStats_FullMethodName            = "/statistics.StatisticsService/GetPostStats"
	StatisticsService_GetPostViewsTimeline_FullMethodName    = "/statistics.StatisticsService/GetPostViewsTimeline"
	StatisticsService_GetPostLikesTimeline_FullMethodName    = "/statistics.StatisticsService/GetPostLikesTimeline"
	StatisticsService_GetPostCommentsTimeline_FullMethodName = "/statistics.StatisticsService/GetPostCommentsTimeline"
	StatisticsService_GetTopPosts_FullMethodName             = "/statistics.StatisticsService/GetTopPosts"
	StatisticsService_GetTopUsers_FullMethodName             = "/statistics.StatisticsService/GetTopUsers"
)

// StatisticsServiceClient is the client API for StatisticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticsServiceClient interface {
	GetPostStats(ctx context.Context, in *GetPostStatsRequest, opts ...grpc.CallOption) (*GetPostStatsResponse, error)
	GetPostViewsTimeline(ctx context.Context, in *GetPostTimelineRequest, opts ...grpc.CallOption) (*GetTimelineResponse, error)
	GetPostLikesTimeline(ctx context.Context, in *GetPostTimelineRequest, opts ...grpc.CallOption) (*GetTimelineResponse, error)
	GetPostCommentsTimeline(ctx context.Context, in *GetPostTimelineRequest, opts ...grpc.CallOption) (*GetTimelineResponse, error)
	GetTopPosts(ctx context.Context, in *GetTopPostsRequest, opts ...grpc.CallOption) (*GetTopPostsResponse, error)
	GetTopUsers(ctx context.Context, in *GetTopUsersRequest, opts ...grpc.CallOption) (*GetTopUsersResponse, error)
}

type statisticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticsServiceClient(cc grpc.ClientConnInterface) StatisticsServiceClient {
	return &statisticsServiceClient{cc}
}

func (c *statisticsServiceClient) GetPostStats(ctx context.Context, in *GetPostStatsRequest, opts ...grpc.CallOption) (*GetPostStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostStatsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetPostStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetPostViewsTimeline(ctx context.Context, in *GetPostTimelineRequest, opts ...grpc.CallOption) (*GetTimelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTimelineResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetPostViewsTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetPostLikesTimeline(ctx context.Context, in *GetPostTimelineRequest, opts ...grpc.CallOption) (*GetTimelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTimelineResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetPostLikesTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetPostCommentsTimeline(ctx context.Context, in *GetPostTimelineRequest, opts ...grpc.CallOption) (*GetTimelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTimelineResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetPostCommentsTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetTopPosts(ctx context.Context, in *GetTopPostsRequest, opts ...grpc.CallOption) (*GetTopPostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopPostsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetTopPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetTopUsers(ctx context.Context, in *GetTopUsersRequest, opts ...grpc.CallOption) (*GetTopUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopUsersResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetTopUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticsServiceServer is the server API for StatisticsService service.
// All implementations must embed UnimplementedStatisticsServiceServer
// for forward compatibility.
type StatisticsServiceServer interface {
	GetPostStats(context.Context, *GetPostStatsRequest) (*GetPostStatsResponse, error)
	GetPostViewsTimeline(context.Context, *GetPostTimelineRequest) (*GetTimelineResponse, error)
	GetPostLikesTimeline(context.Context, *GetPostTimelineRequest) (*GetTimelineResponse, error)
	GetPostCommentsTimeline(context.Context, *GetPostTimelineRequest) (*GetTimelineResponse, error)
	GetTopPosts(context.Context, *GetTopPostsRequest) (*GetTopPostsResponse, error)
	GetTopUsers(context.Context, *GetTopUsersRequest) (*GetTopUsersResponse, error)
	mustEmbedUnimplementedStatisticsServiceServer()
}

// UnimplementedStatisticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatisticsServiceServer struct{}

func (UnimplementedStatisticsServiceServer) GetPostStats(context.Context, *GetPostStatsRequest) (*GetPostStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostStats not implemented")
}
func (UnimplementedStatisticsServiceServer) GetPostViewsTimeline(context.Context, *GetPostTimelineRequest) (*GetTimelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostViewsTimeline not implemented")
}
func (UnimplementedStatisticsServiceServer) GetPostLikesTimeline(context.Context, *GetPostTimelineRequest) (*GetTimelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostLikesTimeline not implemented")
}
func (UnimplementedStatisticsServiceServer) GetPostCommentsTimeline(context.Context, *GetPostTimelineRequest) (*GetTimelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostCommentsTimeline not implemented")
}
func (UnimplementedStatisticsServiceServer) GetTopPosts(context.Context, *GetTopPostsRequest) (*GetTopPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopPosts not implemented")
}
func (UnimplementedStatisticsServiceServer) GetTopUsers(context.Context, *GetTopUsersRequest) (*GetTopUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopUsers not implemented")
}
func (UnimplementedStatisticsServiceServer) mustEmbedUnimplementedStatisticsServiceServer() {}
func (UnimplementedStatisticsServiceServer) testEmbeddedByValue()                           {}

// UnsafeStatisticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticsServiceServer will
// result in compilation errors.
type UnsafeStatisticsServiceServer interface {
	mustEmbedUnimplementedStatisticsServiceServer()
}

func RegisterStatisticsServiceServer(s grpc.ServiceRegistrar, srv StatisticsServiceServer) {
	// If the following call pancis, it indicates UnimplementedStatisticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatisticsService_ServiceDesc, srv)
}

func _StatisticsService_GetPostStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetPostStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetPostStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetPostStats(ctx, req.(*GetPostStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetPostViewsTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetPostViewsTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetPostViewsTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetPostViewsTimeline(ctx, req.(*GetPostTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetPostLikesTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetPostLikesTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetPostLikesTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetPostLikesTimeline(ctx, req.(*GetPostTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetPostCommentsTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetPostCommentsTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetPostCommentsTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetPostCommentsTimeline(ctx, req.(*GetPostTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetTopPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetTopPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetTopPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetTopPosts(ctx, req.(*GetTopPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetTopUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetTopUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetTopUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetTopUsers(ctx, req.(*GetTopUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatisticsService_ServiceDesc is the grpc.ServiceDesc for StatisticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatisticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "statistics.StatisticsService",
	HandlerType: (*StatisticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPostStats",
			Handler:    _StatisticsService_GetPostStats_Handler,
		},
		{
			MethodName: "GetPostViewsTimeline",
			Handler:    _StatisticsService_GetPostViewsTimeline_Handler,
		},
		{
			MethodName: "GetPostLikesTimeline",
			Handler:    _StatisticsService_GetPostLikesTimeline_Handler,
		},
		{
			MethodName: "GetPostCommentsTimeline",
			Handler:    _StatisticsService_GetPostCommentsTimeline_Handler,
		},
		{
			MethodName: "GetTopPosts",
			Handler:    _StatisticsService_GetTopPosts_Handler,
		},
		{
			MethodName: "GetTopUsers",
			Handler:    _StatisticsService_GetTopUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "statistics.proto",
}
