openapi: 3.0.3
info:
  title: Social Network API
  description: API for social network user management
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /api/auth/register:
    post:
      summary: Register a new user
      description: Create a new user account
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/auth/login:
    post:
      summary: Authenticate user
      description: Login with username and password
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/users/profile:
    get:
      summary: Get user profile
      description: Retrieve authenticated user profile data
      tags:
        - User Management
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update user profile
      description: Update authenticated user profile data
      tags:
        - User Management
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProfileRequest'
      responses:
        '200':
          description: User profile updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RegisterRequest:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 50
          example: misha567889
        email:
          type: string
          format: email
          example: myukondrashin_1@edu.hse.ru
        password:
          type: string
          minLength: 6
          maxLength: 72
          example: soa-course-bruh
        first_name:
          type: string
          maxLength: 50
          example: Mikhail
        last_name:
          type: string
          maxLength: 50
          example: Kondrashin
        birth_date:
          type: string
          format: date
          example: 2004-12-11
        phone_number:
          type: string
          example: '+01234567890'

    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: misha567889
        password:
          type: string
          example: soa-course-bruh

    UpdateProfileRequest:
      type: object
      properties:
        first_name:
          type: string
          maxLength: 50
          example: Mikhail
        last_name:
          type: string
          maxLength: 50
          example: Kondrashin
        email:
          type: string
          format: email
          example: myukondrashin_1@edu.hse.ru
        birth_date:
          type: string
          format: date
          example: 2004-12-11
        phone_number:
          type: string
          example: '+01234567890'

    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        username:
          type: string
          example: misha567889
        email:
          type: string
          format: email
          example: myukondrashin_1@edu.hse.ru
        first_name:
          type: string
          example: Mikhail
        last_name:
          type: string
          example: Kondrashin
        birth_date:
          type: string
          format: date
          example: 2004-12-11
        phone_number:
          type: string
          example: '+01234567890'
        created_at:
          type: string
          format: datetime
        updated_at:
          type: string
          format: datetime

    AuthResponse:
      type: object
      properties:
        token:
          type: string
          example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
        user:
          $ref: '#/components/schemas/User'

    Error:
      type: object
      properties:
        error:
          type: string
          example: Something went wrong
